<div class="StreamsFooter StreamsFooter--fixed">
	<ul class="StreamsFooter-list u-cf">
		<li class="StreamsFooter-item">
			<a href="<?php echo So_SeoLink('index.php?link1=about'); ?>" rel="noopener"><?php echo $so['lang']['terms_about']; ?></a>
		</li>
		<li class="StreamsFooter-item">
			<a href="<?php echo So_SeoLink('index.php?link1=tos'); ?>" rel="noopener"><?php echo $so['lang']['terms']; ?></a>
		</li>
		<li class="StreamsFooter-item">
			<a href="<?php echo So_SeoLink('index.php?link1=privacy'); ?>" rel="noopener"><?php echo $so['lang']['terms_privacy']; ?></a>
		</li>
		<li class="StreamsFooter-item StreamsFooter-copyright">© <?php echo date('Y'); ?> <?php echo $so['config']['site_name']; ?></li>
	</ul>
</div>