<?php $so['loggedin'] = false; ?>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<!-- page-header -->
<div class="page-header">
    <div class="container">
        <div class="row">
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                <div class="page-caption">
                    <h1 class="page-title"><?php echo $so['lang']['terms_about']; ?></h1>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /.page-header-->
<!-- news -->
<div class="card-section">
    <div class="container">
        <div class="card-block bg-white mb30">
            <div class="row">
                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                    <!-- section-title -->
                    <div class="section-title mb-0">
                        <?php echo $so['lang']['site_about']; ?>
                    </div>
                    <!-- /.section-title -->
                </div>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 text-center">
                © <?php echo date("Y"); ?> <?php echo $so['config']['site_name']; ?> / <a href="<?php echo So_SeoLink('index.php?link1=welcome'); ?>"><b><?php echo $so['lang']['home_page']; ?></b></a>
            </div>
        </div>
    </div>
</div>
<?php echo So_GetPage('footer/content'); ?>
<style>
    body { -webkit-font-smoothing: antialiased; text-rendering: optimizeLegibility; font-family: 'Overpass', sans-serif; letter-spacing: 0px; font-size: 17px; color: #8d8f90; font-weight: 400; line-height: 32px; background-color: #edefef; }
    h1, h2, h3, h4, h5, h6 { color: #25292a; margin: 0px 0px 10px 0px; font-family: 'Overpass', sans-serif; font-weight: 700; letter-spacing: -1px; line-height: 1; }
    h1 { font-size: 34px; }
    h2 { font-size: 28px; line-height: 38px; }
    h3 { font-size: 22px; line-height: 32px; }
    h4 { font-size: 20px; }
    h5 { font-size: 17px; }
    h6 { font-size: 12px; }
    p { margin: 0 0 20px; line-height: 1.7; }
    p:last-child { margin: 0px; }
    ul, ol { }
    a { text-decoration: none; color: #8d8f90; -webkit-transition: all 0.3s; -moz-transition: all 0.3s; transition: all 0.3s; }
    a:focus, a:hover { text-decoration: none; color: #f85759; }



    .page-header { background: url(<?php echo $so['config']['theme_url']; ?>/img/pageheader.jpg)no-repeat; position: relative; background-size: cover; }
    .page-caption { padding-top: 170px; padding-bottom: 174px; }
    .page-title { font-size: 46px; line-height: 1; color: #fff; font-weight: 600; text-align: center; }

    .card-section { position: relative; bottom: 60px; }
    .card-block { padding: 80px; }
    .section-title { margin-bottom: 60px; }
</style>