<?php
if (!isset($_GET['page'])) {
    $_GET['page'] = 'dashboard';
}
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Required meta tags-->
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="au theme template">
        <meta name="author" content="Hau Nguyen">
        <meta name="keywords" content="au theme template">
        <meta name="robots" content="noindex">
        <meta name="googlebot" content="noindex">
        <!-- Title Page-->
        <title>Dashboard</title>

        <script type="text/javascript" src="<?php echo $so['config']['theme_url']; ?>/javascript/jquery-3.3.1.min.js"></script>
        <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
        <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
        <!------ Include the above in your HEAD tag ---------->
        <link href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" type="text/css" rel="stylesheet">
        <style>
            /*
 * Base structure
 */

            /* Move down content because we have a fixed navbar that is 50px tall */
            body {
                padding-top: 50px;
            }


            /*
             * Global add-ons
             */

            .sub-header {
                padding-bottom: 10px;
                border-bottom: 1px solid #eee;
            }

            /*
             * Top navigation
             * Hide default border to remove 1px line.
             */
            .navbar-fixed-top {
                border: 0;
            }

            /*
             * Sidebar
             */

            /* Hide for mobile, show later */
            .sidebar {
                display: none;
            }
            @media (min-width: 768px) {
                .sidebar {
                    position: fixed;
                    top: 51px;
                    bottom: 0;
                    left: 0;
                    z-index: 1000;
                    display: block;
                    padding: 20px;
                    overflow-x: hidden;
                    overflow-y: auto; /* Scrollable contents if viewport is shorter than content. */
                    background-color: #f5f5f5;
                    border-right: 1px solid #eee;
                }
            }

            /* Sidebar navigation */
            .nav-sidebar {
                margin-right: -21px; /* 20px padding + 1px border */
                margin-bottom: 20px;
                margin-left: -20px;
            }
            .nav-sidebar > li > a {
                padding-right: 20px;
                padding-left: 20px;
            }
            .nav-sidebar > .active > a,
            .nav-sidebar > .active > a:hover,
            .nav-sidebar > .active > a:focus {
                color: #fff;
                background-color: #428bca;
            }


            /*
             * Main content
             */

            .main {
                padding: 20px;
            }
            @media (min-width: 768px) {
                .main {
                    padding-right: 40px;
                    padding-left: 40px;
                }
            }
            .main .page-header {
                margin-top: 0;
            }


            /*
             * Placeholder dashboard ideas
             */

            .placeholders {
                margin-bottom: 30px;
                text-align: center;
            }
            .placeholders h4 {
                margin-bottom: 0;
            }
            .placeholder {
                margin-bottom: 20px;
            }
            .placeholder img {
                display: inline-block;
                border-radius: 50%;
            }
            .glyphicon-lg
            {
                font-size:4em
            }
            .info-block
            {
                border-right:5px solid #E6E6E6;margin-bottom:25px
            }
            .info-block .square-box
            {
                width:100px;min-height:110px;margin-right:22px;text-align:center!important;background-color:#676767;padding:20px 0
            }
            .info-block.block-info
            {
                border-color:#20819e
            }
            .info-block.block-info .square-box
            {
                background-color:#20819e;color:#FFF
            }
            .nav-sidebar > li > ul > li {
                border-bottom: solid 1px #f1f1f1;
                padding: 5px;
                list-style: none;
            }
            .nav-sidebar > li > ul > li a {
                text-decoration: none;
                cursor: pointer;
            }
            #sub li.active.has-sub, #sub li.active.has-sub > a, #sub li.active.has-sub > a:focus {
                color: #fff;
                background-color: #428bca;
            }
        </style>
        <script>
            function So_Requests() {
                return "<?php echo $so['config']['site_url'] . '/requests.php'; ?>";
            }
            function So_DeleteUser(user_id) {
                $.post(So_Requests() + '?type=delete-account', {
                    user_id: user_id
                }, function (data) {
                    if (data.status == 200) {
                        $('#result-' + user_id).remove();
                    } else {
                        return false;
                    }
                });
            }
            function So_DeletePost(post_id) {
                $.get(So_Requests() + '?type=delete-post', {
                    post_id: post_id
                }, function (data) {
                    if (data.status == 200) {
                        $('#result-' + post_id).remove();
                    } else {
                        return false;
                    }
                });
            }
            function So_SearchUser(user) {
                $.get(So_Requests() + '?type=search-admin-user', {
                    user: user
                }, function (data) {
                    if (data.status == 200) {
                        $('#default-list').hide();
                        $('#search-list').html(data.html);
                    } else {
                        $('#default-list').show();
                        $('#search-list').html('');
                    }
                });
            }
        </script>
    </head>
    <body class="animsition">
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="<?php echo $so['config']['site_url']; ?>">
                        <?php echo $so['config']['site_name']; ?>
                    </a>
                </div>
            </div>
        </nav>

        <div class="container-fluid">
            <div class="col-sm-3 col-md-2 sidebar">
                <ul class="nav nav-sidebar">
                    <li <?php if (!isset($_GET['page']) || $_GET['page'] == 'dashboard') { ?>class="active has-sub"<?php } ?>>
                        <a class="js-arrow" href="<?php echo $so['config']['site_url']; ?>/admincp">
                            <i class="fas fa-tachometer-alt"></i>
                            Dashboard
                        </a>
                    </li>
                    <li <?php if ($_GET['page'] == 'users') { ?>class="active has-sub"<?php } ?>>
                        <a href="<?php echo $so['config']['site_url']; ?>/admincp/users">
                            <i class="fas fa-users"></i>
                            Users
                        </a>
                    </li>
                    <!--<li <?php if ($_GET['page'] == 'posts') { ?>class="active has-sub"<?php } ?>>
                        <a href="<?php echo $so['config']['site_url']; ?>/admincp/posts">
                            <i class="fas fa-paint-brush"></i>
                            Posts
                        </a>
                    </li>-->
                    <li <?php if ($_GET['page'] == 'settings') { ?>class="active has-sub"<?php } ?>>
                        <a href="<?php echo $so['config']['site_url']; ?>/admincp/settings">
                            <i class="fas fa-sliders-h"></i>
                            Settings
                        </a>
                    </li>
                    <li <?php if ($_GET['page'] == 'ads') { ?>class="active has-sub"<?php } ?>>
                        <a href="<?php echo $so['config']['site_url']; ?>/admincp/ads">
                            <i class="fab fa-paypal"></i>
                            Adsense
                        </a>
                    </li>
                    <li <?php if ($_GET['page'] == 'custom-settings') { ?>class="active has-sub"<?php } ?>>
                        <a href="<?php echo $so['config']['site_url']; ?>/admincp/custom-settings">
                            <i class="fas fa-pencil-alt"></i>
                            Custom settings
                        </a>
                    </li>
                    <li <?php if ($_GET['page'] == 'design-settings') { ?>class="active has-sub"<?php } ?>>
                        <a href="<?php echo $so['config']['site_url']; ?>/admincp/design-settings">
                            <i class="fas fa-object-ungroup"></i>
                            Design settings
                        </a>
                    </li>
                    <li <?php if ($_GET['page'] == 'stickers-store') { ?>class="active has-sub"<?php } ?>>
                        <a href="<?php echo $so['config']['site_url']; ?>/admincp/stickers-store">
                            <i class="fas fa-magic"></i>
                            Stickers Store
                        </a>
                        <ul id="sub">
                            <li>
                                <a href="<?php echo $so['config']['site_url']; ?>/admincp/stickers-store">
                                    Create Stickers Package
                                </a>
                            </li>
                            <li <?php if ($_GET['page'] == 'list-stickers-store') { ?>class="active has-sub"<?php } ?>>
                                <a href="<?php echo $so['config']['site_url']; ?>/admincp/list-stickers-store">
                                    Package List
                                </a>
                            </li>
                        </u>
                    </li>
                </ul>
                <p><?php echo $so['lang']['script_version']; ?>: <?php echo $so['config']['version']; ?></p>
            </div>
            <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
                <?php echo So_GetPage('admincp/content'); ?>
            </div>
        </div>
        <script type="text/javascript" src="<?php echo $so['config']['theme_url']; ?>/javascript/jquery.form.min.js"></script>
    </body>
</html>
<!-- end document-->
