<style>
a {
	color: <?php echo $so['config']['color_link']; ?>;
}
.header-content {
	background-color: <?php echo $so['config']['header_background']; ?>!important;
    border-bottom: solid 1px <?php echo $so['config']['color_border']; ?>!important;
}
input#search-query {
    background-color: <?php echo $so['config']['search_background']; ?>!important;
    border-left: solid 1px <?php echo $so['config']['border_search_background']; ?>!important;
    border-right: solid 1px <?php echo $so['config']['border_search_background']; ?>!important;
}
.EdgeButton--primary, .EdgeButton--primary:focus {
	background-color: <?php echo $so['config']['header_background']; ?>!important;
	border: 1px solid <?php echo $so['config']['border_button']; ?>!important;
}
.adsfsafas span.count {
	background-color: <?php echo $so['config']['color_total_notifications']; ?>!important;
}
a.DashboardProfileCard-bg.u-bgUserColor.u-block {
    border-bottom: solid 4px <?php echo $so['config']['color_border']; ?>!important;
}
.profile-container-top .profile-cover {
	background-color: <?php echo $so['config']['cover_background']; ?>!important;
}
.u-bgUserColor, .u-bgUserColorHover:hover, .u-bgUserColorHover:focus {
	background-color: <?php echo $so['config']['header_background_two']; ?>!important;
}
.primary-btn, .notifying .device-follow-button, .button-group-item .content.selected {
	background-color: <?php echo $so['config']['border_search_background']; ?>!important;
}
</style>