<div class="AdaptiveMediaOuterContainer">
    <div class="AdaptiveMedia is-video has-autoplayable-media" data-autoplaying-media="true">
        <div class="AdaptiveMedia-container">
            <div class="AdaptiveMedia-video">
                <div class="AdaptiveMedia-videoContainer">
                    <div class="PlayableMedia PlayableMedia--gif watched playable-media-loaded">
                        <div class="PlayableMedia-container">
                            <div class="PlayableMedia-player" style="padding-bottom: 70.0%; background-image:url('https://media.giphy.com/media/<?php echo $so['origin']['postGif']; ?>/giphy_s.gif')">
                                <div class="PlayableMedia-reactWrapper">
                                    <div style="cursor: pointer; height: 100%; width: 100%; position: relative; color: rgba(255, 255, 255, 0.85); font-size: 13px; font-weight: 400;line-height: normal; transform: translateZ(0px);">
                                        <div role="button" tabindex="0" style="position: absolute; height: 100%; width: 100%;">
                                            <div style="position: relative; width: 100%; height: 100%; background-color: transparent;">
                                                <video id="video-gif-<?php echo $so['origin']['post_id']; ?>" src="https://media.giphy.com/media/<?php echo $so['origin']['postGif']; ?>/giphy.mp4" poster="https://media.giphy.com/media/<?php echo $so['origin']['postGif']; ?>/giphy_s.gif" loop="" playsinline=""  muted="muted" style="width: 100%; height: 100%; position: absolute; background-color: black; transform: rotate(0deg) scale(1);"></video>
                                            </div>
                                            <div class="click-toplay-pause-video" data-post-id="<?php echo $so['origin']['post_id']; ?>" data-status="true"></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        // Get media - with autoplay disabled (audio or video)
        var media = $('video').not("[autoplay='autoplay']");
        var tolerancePixel = 150;

        function checkMedia() {
            // Get current browser top and bottom
            var scrollTop = $(window).scrollTop() + tolerancePixel;
            var scrollBottom = $(window).scrollTop() + $(window).height() - tolerancePixel;
            media.each(function (index, el) {
                var yTopMedia = $(this).offset().top;
                var yBottomMedia = $(this).height() + yTopMedia;

                if (scrollTop < yBottomMedia && scrollBottom > yTopMedia) {
                    $(this).get(0).play();
                } else {
                    $(this).get(0).pause();

                }
            });
        }
        $(document).on('scroll', checkMedia);
    });
</script>