<?php
$classSticker = new Sticker();
?>
<div>
    <div class="stickers-header">
        <div class="pull-left">
            <ul>
                <li>
                    <a class="pointer" onclick="So_GetPackageTypeComment(<?php echo $classSticker->So_StickerStoreData(2)['id']; ?>, <?php echo $so['story']['post_id']; ?>);">
                        <img src="<?php echo $classSticker->So_StickerStoreData(2)['image']; ?>" />
                    </a>
                </li>
                <?php
                foreach ($classSticker->So_GetMyAllStickers() as $so['pack']) {
                    ?>
                    <li>
                        <a class="pointer" onclick="So_GetPackageTypeComment(<?php echo $so['pack']['id']; ?>, <?php echo $so['story']['post_id']; ?>);">
                            <img src="<?php echo $so['pack']['image']; ?>" />
                        </a>
                    </li>
                <?php } ?>
            </ul>
        </div>
        <div class="pull-left" onclick="So_GetStickersStoreComment(<?php echo $so['story']['post_id']; ?>);" style="text-align:  center;width: 45px;height: 50px;padding: 12px 0px;border-left: solid 1px #f1f1f1;;">
            <a class="pointer">
                <i class="fas fa-store"></i>
            </a>
        </div>
    </div>
    <div class="stickers-body">
        <div class="meep">
            <?php foreach ($classSticker->So_GetAllStickers(2) as $so['sticker']) { ?>
                <div class="pull-left">
                    <div id="package-sticker">
                        <div class="pointer safdasa" id="submit-form-sticker-comment" data-sticker="<?php echo str_replace($so['config']['site_url'] . '/', "", $so['sticker']['image']); ?>" data-post="<?php echo $so['story']['post_id']; ?>">
                            <img src="<?php echo $so['sticker']['image']; ?>" />
                        </div>
                    </div>
                </div>
            <?php } ?>
        </div>
    </div>
</div>