<h1 class="page-header">Dashboard</h1>
<div class="row placeholders">
    <div class="col-xs-6 col-sm-3 placeholder">
        <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
        <h4>Total Users</h4>
        <span class="text-muted"><?php echo So_TotalUsers(); ?></span>
    </div>
    <div class="col-xs-6 col-sm-3 placeholder">
        <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
        <h4>Total Posts</h4>
        <span class="text-muted"><?php echo So_TotalPosts(); ?></span>
    </div>
</div>