<div class="ProfileOnboarding-profilePhoto introduce-yourself" id="introduce-yourself">
    <div class="ProfileOnboarding-header">
        <div class="dismiss js-action-dismiss">
            <span class="Icon"><i class="fas fa-times"></i></span>
        </div>
        <div class="ProfileOnboarding-title"><?php echo $so['lang']['pike_a_cover_picture']; ?></div>
        <div class="ProfileOnboarding-subtitle"><?php echo $so['lang']['have_some_picture_cover']; ?></div>
        <form class="form-horizontal" id="change-profile-cover" method="post">
            <fieldset>
                <div class="alert-errors"></div>
                <div class="fdlfjslfsj">
                    <div class="wsdfsdr">
                        <div class="efsaesed" style="background: url(<?php echo $so['config']['site_url']; ?>/upload/images/d-avatar.png);background-size: 100% 100%;">
                            <span class="btn-upload">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-camera"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
                            </span>
                        </div>
                        <label for="__FileInput_1" class="rn-1p0dtai rn-1loqt21 rn-1d2f490 rn-u8s1d rn-zchlnj rn-ipm5af rn-184en5c"></label>
                        <input style="top: 90px;left: 68px;" accept="image/jpeg,image/png" type="file" name="cover" id="file-image" onchange="So_SubmitFormProfileCover();"/>
                    </div>
                    <div class="publisher-hidden-option">
                        <div id="progress">
                            <span id="percent">0%</span>
                            <div class="progress">
                                <div id="bar" class="progress-bar active"></div> 
                            </div>
                            <div class="clear"></div>
                        </div>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>
<script type="text/javascript">
    $(function () {
        var bar = $('#bar');
        var percent = $('#percent');
        $('form#change-profile-cover').ajaxForm({
            url: So_Requests() + '?type=change-profile-cover',
            beforeSend: function () {
                var percentVal = '0%';
                bar.width(percentVal);
                percent.html(percentVal);
                $('.askfjafklj.pull-right').css('opacity', '0.5');
                $('.askfjafklj.pull-right').find('a').attr('onclick', '');
            },
            uploadProgress: function (event, position, total, percentComplete) {
                var percentVal = percentComplete + '%';
                bar.width(percentVal);
                $('#progress').slideDown(200);
                percent.html(percentVal);
            },
            success: function (data) {
                $('#progress').slideUp(200);
                if (data.status == 200) {
                    window.location.href = '<?php echo So_SeoLink('index.php?link1=home'); ?>';
                } else if (data.status == 400) {
                    $('.alert-errors').html(data.errors);
                    $('.askfjafklj.pull-right').css('opacity', '1');
                    $('.askfjafklj.pull-right').find('a').attr('onclick', 'So_SubmitFormProfileCover();');
                } else {
                    return false;
                }
            }
        });
    });
    function So_SubmitFormProfileCover() {
        $('form#change-profile-cover').submit();
    }
</script>