<div class="ProfileOnboarding-bio introduce-yourself" id="introduce-yourself">
    <div class="ProfileOnboarding-header">
        <div class="dismiss js-action-dismiss"><span class="Icon"><i class="fas fa-times"></i></span></div>
        <div class="ProfileOnboarding-title"><?php echo $so['lang']['introduce_yourself']; ?></div>
        <div class="ProfileOnboarding-subtitle"><?php echo $so['lang']['introduce_who_you_are']; ?></div>
    </div>
    <div class="ProfileHeaderCardEditing-bioRich ProfileHeaderCardEditing-item">
        <div class="RichEditor RichEditor--emojiPicker u-borderUserColorLight">
            <div class="RichEditor-container u-borderRadiusInherit">
                <form class="form-horizontal" id="change-about-me" method="post">
                    <fieldset>
                        <div class="fdlfjslfsj">
                            <div class="wsdfsdr">
                                <textarea style="border-color: transparent;border-radius: 10px;width: 100%;padding: 10px;border: solid 1px #f1f1f1;" id="user_description" class="ProfileHeaderCardEditing-editableField rich-editor u-borderUserColorLight is-showPlaceholder" name="about" spellcheck="true" aria-multiline="true" data-placeholder="Bio" role="textbox" tabindex="2"></textarea>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(function () {
        $('form#change-about-me').ajaxForm({
            url: So_Requests() + '?type=change-about-me',
            beforeSend: function () {
                
            },
            success: function (data) {
                if (data.status == 200) {
                    $('form#change-about-me').remove();
                } else {
                    return false;
                }
            }
        });
    });
</script>