<style>
.video-js .vjs-tech {
  width: 100% !important;
  height: 100% !important;
}
div#finished-live {
    width: 100%;
    height: 100%;
    text-align: center;
    font-size: 20px;
    margin: 90px auto;
}
.vjs-modal-dialog-content {
	display: none;
}
</style>
<?php
header('Access-Control-Allow-Origin: *'); 
$classUser = new User();
$secret_key = $classUser->So_UserData($so['story']['user_id'])['secret_key'];
$cover = $classUser->So_UserData($so['story']['user_id'])['cover'];
?>
<div class="AdaptiveMediaOuterContainer">
    <div class="AdaptiveMedia is-video has-autoplayable-media" data-autoplaying-media="true">
        <div class="AdaptiveMedia-container">
            <div class="PlayableMedia-player" style="padding-bottom: 56.49999999999999%;">
                <div class="PlayableMedia-reactWrapper">
                    <div style="cursor: pointer; height: 100%; width: 100%; position: relative; color: rgba(255, 255, 255, 0.85); font-size: 13px; font-weight: 400;line-height: normal; transform: translateZ(0px);">
                        <div role="button" tabindex="0" style="position: absolute; height: 100%; width: 100%;">
                            <div id="safdasfms-live-video-<?php echo $so['story']['post_id']; ?>" style="position: relative; width: 100%; height: 100%; background-color: transparent;">
                                <script src="https://unpkg.com/videojs-contrib-hls/dist/videojs-contrib-hls.js"></script>
								<video height="260px" id="live-video-<?php echo $so['story']['post_id']; ?>" class="video-js"  style="width: 100%; position: absolute; background-color: black; transform: rotate(0deg) scale(1);" controls muted="muted" controls preload="auto" poster="<?php echo $cover; ?>"
								data-setup='{}'>
									<source src="https://live.<?php echo str_replace("https://www.", "", $so['config']['site_url']); ?>/live/<?php echo $secret_key; ?>.m3u8" type="application/x-mpegURL">
									<div id="error"></div>
								</video>
								<script src="https://unpkg.com/video.js/dist/video.js"></script>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
#safdasfms-live-video-<?php echo $so['story']['post_id']; ?> .vjs-error .vjs-error-display::before {
	content: '<?php echo $so['lang']['this_live_was_finished']; ?>'!important;
	font-size: 15px;
}
</style>