<li class="DMTokenizedMultiselectSuggestion DMTypeaheadSuggestions-item" data-token-id="<?php echo $so['list']['user_id']; ?>" data-token-text="<?php echo $so['list']['name']; ?>" role="option" tabindex="-1" id="tokenizedMultiselectHighlight<?php echo $so['list']['user_id']; ?>" aria-selected="true">
    <div class="DMTokenizedMultiselectSuggestion-body">
        <div class="DMTypeaheadItem">
            <div class="DMTypeaheadItem-avatar" aria-hidden="true">
                <div class="DMAvatar DMAvatar--1 u-chromeOverflowFix">
                    <span class="DMAvatar-container">
                        <img class="DMAvatar-image" src="<?php echo $so['list']['avatar']; ?>" alt="<?php echo $so['list']['name']; ?>" title="<?php echo $so['list']['name']; ?>">
                    </span>
                </div>
            </div>
            <div class="DMTypeaheadItem-body">
                <div class="DMTypeaheadItem-title account-group">
                    <b class="fullname"><?php echo $so['list']['name']; ?></b>
                    <span class="UserBadges"></span>
                    <span class="UserNameBreak">&nbsp;</span>
                    <span class="username u-dir u-textTruncate" dir="ltr">@<b><?php echo $so['list']['username']; ?></b></span>
                </div>
            </div>
        </div>
    </div>
</li>