<div class="DMInbox-empty" style="display: block;">
    <div class="DMEmptyState">
        <h2 class="DMEmptyState-header">
            <?php echo $so['lang']['send_and_get_a_message']; ?>
        </h2>
        <div class="DMEmptyState-details">
            <p><?php echo $so['lang']['direct_is']; ?></p>
        </div>
        <div class="DMEmptyState-cta">
            <button onclick="So_GetSearch();" type="button" class="EdgeButton EdgeButton--primary dm-new-button">
                <?php echo $so['lang']['start_to_conversation']; ?>
            </button>
        </div>
    </div>
</div>