<a class="pointer post-additional-info inline-items" style="border-top: none;padding: 0px;" href="<?php echo $so['story']['html_url']; ?>" target="_blank">
	<div class="url-embed-content">
		<div class="html-image" style="margin-left: 0px;">
			<img src="<?php echo $so['story']['html_image']; ?>" />
		</div>
		<div class="url-embed-body">
			<div class="html-title">
				<?php echo $so['story']['html_title']; ?>
			</div>
			<div class="html-body">
				<?php echo $so['story']['html_body']; ?>
			</div>
		</div>
	</div>
</a>