<div class="safaasfa-create-ads">
	<div class="header-create-ads">
		<?php echo $so['lang']['choose_a_goal']; ?>
	</div>
	<div class="body-create-ads">
		<div>
			<div class="body-header-create-ads" style="font-family: Arial, sans-serif; font-size: 24px; line-height: 28px; letter-spacing: normal; overflow-wrap: normal; text-align: center; color: rgb(28, 30, 33);">
				<?php echo $so['lang']['how_do_you_want_expand']; ?>
			</div>
			<div class="_3-8p" style="font-family: Arial, sans-serif; font-size: 16px; line-height: 20px; letter-spacing: normal; overflow-wrap: normal; text-align: center; color: rgb(96, 103, 112);">
				<?php echo $so['lang']['create_ads_help_you']; ?>
			</div>
		</div>
		<div>
			<div class="list-type-create-ads">
				<div class="_3u8q">
					<div class="_3-95" style="font-family: Arial, sans-serif; font-size: 12px; line-height: 16px; letter-spacing: normal; overflow-wrap: normal; text-align: left; color: rgb(96, 103, 112);">
						<?php echo $so['lang']['new']; ?>
					</div>
				</div>
				<div class="_13ch">
				   <div tabindex="0" role="button">
					  <div class="_31uc" tabindex="0" role="button">
						 <div direction="left" class="clearfix">
							<div class="_ohe lfloat">
								<img class="_31ud img" src="https://www.facebook.com/images/pages/lwi/strategyOngoingPromotion.png" alt="">
							</div>
							<div class="">
							   <div direction="right" class="clearfix">
								  <div class="_ohf rfloat">
									 <div class="_6a">
										<div class="_6a _6b" style="height: 100px;"></div>
										<div class="_6a _6b">
											<span class="_3-91 _kcu">
												<img class="_kcw img" src="https://static.xx.fbcdn.net/rsrc.php/v3/y4/r/zO2Ngqb-dh-.png" alt="" height="16" width="16">
											</span>
										</div>
									 </div>
								  </div>
								  <div class="">
									 <div class="_3za7 _6a">
										<div class="_6a _6b">
											<div style="font-family: Arial, sans-serif; font-size: 14px; line-height: 18px; letter-spacing: normal; font-weight: bold; overflow-wrap: normal; text-align: left; color: rgb(28, 30, 33);">
												Obter anúncios automáticos personalizados
											</div>
											<div class="_3-8w" style="font-family: Arial, sans-serif; font-size: 14px; line-height: 18px; letter-spacing: normal; overflow-wrap: normal; text-align: left; color: rgb(28, 30, 33);">
												Responda a algumas perguntas para encontrar os anúncios certos para a sua empresa
											</div>
										</div>
									 </div>
								  </div>
							   </div>
							</div>
						 </div>
					  </div>
				   </div>
				</div>
				<div class="_13ch">
				   <div tabindex="0" role="button">
					  <div class="_31uc" tabindex="0" role="button">
						 <div direction="left" class="clearfix">
							<div class="_ohe lfloat">
								<img class="_31ud img" src="https://www.facebook.com/images/pages/lwi/website.png" alt="">
							</div>
							<div class="">
							   <div direction="right" class="clearfix">
								  <div class="_ohf rfloat">
									 <div class="_6a">
										<div class="_6a _6b" style="height: 100px;"></div>
										<div class="_6a _6b">
											<span class="_3-91 _kcu">
												<img class="_kcw img" src="https://static.xx.fbcdn.net/rsrc.php/v3/y4/r/zO2Ngqb-dh-.png" alt="" height="16" width="16">
											</span>
										</div>
									 </div>
								  </div>
								  <div class="">
									 <div class="_3za7 _6a">
										<div class="_6a _6b">
											<div style="font-family: Arial, sans-serif; font-size: 14px; line-height: 18px; letter-spacing: normal; font-weight: bold; overflow-wrap: normal; text-align: left; color: rgb(28, 30, 33);">
												Obter anúncios automáticos personalizados
											</div>
											<div class="_3-8w" style="font-family: Arial, sans-serif; font-size: 14px; line-height: 18px; letter-spacing: normal; overflow-wrap: normal; text-align: left; color: rgb(28, 30, 33);">
												Responda a algumas perguntas para encontrar os anúncios certos para a sua empresa
											</div>
										</div>
									 </div>
								  </div>
							   </div>
							</div>
						 </div>
					  </div>
				   </div>
				</div>
			</div>
		</div>
	</div>
</div>