<div class="asljdklajas">
	<span aria-pressed="false" aria-label="Like" class="_iuw" data-testid="reaction_1" href="javascript:void(0);" role="button" tabindex="-1" onclick="So_RegisterReaction(<?php echo $so['story']['post_id']; ?>, 'reaction_like');">
	   <div class="_39m _1ef2" data-reaction="1">
		  <div class="_39n">
			 <div class="_1ef0" style="display: inline-block; line-height: 0; font-size: 0px;">
				<div class="emoji emoji--like"><div class="emoji__hand"><div class="emoji__thumb"></div></div></div>	 
			</div>
			 <div class="_d6l">
				<div class="_4sm1"><?php echo $so['lang']['like']; ?></div>
			 </div>
		  </div>
	   </div>
	</span>
	<span aria-pressed="false" aria-label="Love" class="_iuw" data-testid="reaction_2" href="javascript:void(0);" role="button" tabindex="-1" onclick="So_RegisterReaction(<?php echo $so['story']['post_id']; ?>, 'reaction_love');">
	   <div class="_39m _1ef2" data-reaction="2">
		  <div class="_39n">
			 <div class="_1ef0" style="display: inline-block; line-height: 0; font-size: 0px;">
				<div class="emoji emoji--love"><div class="emoji__heart"></div></div>
			 </div>
			 <div class="_d6l">
				<div class="_4sm1"><?php echo $so['lang']['love']; ?></div>
			 </div>
		  </div>
	   </div>
	</span>
	<span aria-pressed="false" aria-label="Haha" class="_iuw" data-testid="reaction_3" href="javascript:void(0);" role="button" tabindex="-1" onclick="So_RegisterReaction(<?php echo $so['story']['post_id']; ?>, 'reaction_haha');">
	   <div class="_39m _1ef2" data-reaction="3">
		  <div class="_39n">
			<div class="_1ef0" style="display: inline-block; line-height: 0; font-size: 0px;">
				<div class="emoji emoji--haha"><div class="emoji__face"><div class="emoji__eyes"></div><div class="emoji__mouth"><div class="emoji__tongue"></div></div></div></div>
			</div>
			 <div class="_d6l">
				<div class="_4sm1"><?php echo $so['lang']['haha']; ?></div>
			 </div>
		  </div>
	   </div>
	</span>
	<span aria-pressed="false" aria-label="Wow" class="_iuw" data-testid="reaction_4" href="javascript:void(0);" role="button" tabindex="-1" onclick="So_RegisterReaction(<?php echo $so['story']['post_id']; ?>, 'reaction_wow');">
	   <div class="_39m _1ef2" data-reaction="4">
		  <div class="_39n">
			 <div class="_1ef0" style="display: inline-block; line-height: 0; font-size: 0px;">
				<div class="emoji emoji--wow"><div class="emoji__face"><div class="emoji__eyebrows"></div><div class="emoji__eyes"></div><div class="emoji__mouth"></div></div></div>
			 </div>
			 <div class="_d6l">
				<div class="_4sm1"><?php echo $so['lang']['wow']; ?></div>
			 </div>
		  </div>
	   </div>
	</span>
	<span aria-pressed="false" aria-label="Cry" class="_iuw" data-testid="reaction_5" href="javascript:void(0);" role="button" tabindex="-1" onclick="So_RegisterReaction(<?php echo $so['story']['post_id']; ?>, 'reaction_cry');">
	   <div class="_39m _1ef2" data-reaction="5">
		  <div class="_39n">
			 <div class="_1ef0" style="display: inline-block; line-height: 0; font-size: 0px;">
				<div class="emoji emoji--sad"><div class="emoji__face"><div class="emoji__eyebrows"></div><div class="emoji__eyes"></div><div class="emoji__mouth"></div></div></div>
			 </div>
			 <div class="_d6l">
				<div class="_4sm1"><?php echo $so['lang']['cry']; ?></div>
			 </div>
		  </div>
	   </div>
	</span>
	<span aria-pressed="false" aria-label="Grr" class="_iuw" data-testid="reaction_6" href="javascript:void(0);" role="button" tabindex="-1" onclick="So_RegisterReaction(<?php echo $so['story']['post_id']; ?>, 'reaction_grr');">
	   <div class="_39m _1ef2" data-reaction="6">
		  <div class="_39n">
			 <div class="_1ef0" style="display: inline-block; line-height: 0; font-size: 0px;">
				<div class="emoji emoji--angry"><div class="emoji__face"><div class="emoji__eyebrows"></div><div class="emoji__eyes"></div><div class="emoji__mouth"></div></div></div>
			 </div>
			 <div class="_d6l">
				<div class="_4sm1"><?php echo $so['lang']['grr']; ?></div>
			 </div>
		  </div>
	   </div>
	</span>
</div>