<div class="col-md-12" id="login-form-wp">
    <div class="login-page">
        <div class="login-logo">
            <h1><?php echo $so['config']['site_name']; ?></h1>
        </div>
        <div class="form">
            <div class="alert-errors" style="margin-bottom: 5px;"></div>
            <form class="login-form" method="post" id="login">
                <input type="text" name="email" autocomplete="on" value="" placeholder="<?php echo $so['lang']['username']; ?>, <?php echo $so['lang']['email']; ?>  <?php echo $so['lang']['or']; ?> <?php echo $so['lang']['phone_number']; ?>" />
                <input type="password" name="password" placeholder="<?php echo $so['lang']['password']; ?>"/>
                <p class="message">
                    <a class="forgot" href="<?php echo So_SeoLink('index.php?link1=forgot-password'); ?>" rel="noopener"><?php echo $so['lang']['forgot_password']; ?></a>
                </p>
                <br>
                <button><?php echo $so['lang']['login']; ?></button>
                <hr>
                <p class="message">
                    <?php echo $so['lang']['not_registered']; ?> <a href="<?php echo So_SeoLink('index.php?link1=signup'); ?>">
                        <?php echo $so['lang']['create_account']; ?>
                    </a>
                </p>
            </form>
        </div>
    </div>
</div>
<?php echo So_GetPage('footer/content'); ?>
<style>
    div#container-to-ajax-loading {
        height: auto;
    }
    body {
        background: url(<?php echo $so['config']['theme_url']; ?>/img/mountain.jpg) no-repeat center center fixed;
        height: -webkit-fill-available;
        background-position: center;
        background-size: 100% 100%;
    }
</style>
<script>
    $(function () {
        $('form#login').ajaxForm({
            url: So_Requests() + '?type=signin',
            beforeSend: function () {

            },
            success: function (data) {
                if (data.status == 200) {
                    window.location.href = '<?php echo $so['config']['site_url']; ?>';
                } else if (data.status == 400) {
                    $('.alert-errors').html(data.errors);
                } else {
                    return false;
                }
            }
        });
    });
</script>