<div class="col-md-12" id="login-form-wp">
    <div class="login-page">
        <div class="login-logo">
            <h1><?php echo $so['lang']['password_reset']; ?></h1>
        </div>
        <div class="form">
            <div class="alert-errors" style="margin-bottom: 5px;"></div>
            <form class="login-form" method="post" id="reset">
                <input type="text" name="email" autocomplete="on" value="" placeholder="<?php echo $so['lang']['enter_email']; ?>" />
                <button><?php echo $so['lang']['send_it']; ?></button>
                <hr>
                <p class="message">
                    <?php echo $so['lang']['has_registered']; ?> <a href="<?php echo So_SeoLink('index.php?link1=signin'); ?>">
                        <?php echo $so['lang']['login']; ?>
                    </a>
                </p>
            </form>
        </div>
    </div>
</div>
<?php echo So_GetPage('footer/content'); ?>
<style>
    div#container-to-ajax-loading {
        height: auto;
    }
    body {
        background: url(<?php echo $so['config']['theme_url']; ?>/img/mountain.jpg) no-repeat center center fixed;
        height: -webkit-fill-available;
        background-position: center;
        background-size: 100% 100%;
    }
</style>
<script>
    $(function () {
        $('form#reset').ajaxForm({
            url: So_Requests() + '?type=password-reset',
            beforeSend: function () {

            },
            success: function (data) {
                if (data.status == 200) {
                    $('.alert-errors').html(data.html);
                } else if (data.status == 400) {
                    $('.alert-errors').html(data.errors);
                } else {
                    return false;
                }
            }
        });
    });
</script>