<?php $classUser = new User(); ?>
<div class="col-md-12" id="login-form-wp">
    <div class="login-page">
        <div class="login-logo">
            <h1><?php echo $so['lang']['password_recover']; ?></h1>
        </div>
        <div class="form">
            <div class="alert-errors" style="margin-bottom: 5px;"></div>
            <p>
                <?php echo $so['lang']['enter_new_passowrd']; ?>
            </p>
            <form class="login-form" method="post" id="reset">
                <input type="password" name="password" placeholder="<?php echo $so['lang']['password']; ?>"/>
                <?php if (isset($_GET['token']) && !empty($_GET['token'])) { ?>
                    <input type="hidden" name="token" value="<?php echo $_GET['token']; ?>" />
                <?php } ?>
                <p class="message Form-message">
                    <?php if (!isset($_GET['token']) || empty($_GET['token']) || $classUser->So_CheckExistUserToken($_GET['token']) === false) {
                        echo $so['lang']['invalid_token'];
                    } ?>
                </p>
                <br>
                <button><?php echo $so['lang']['change_password']; ?></button>
                <hr>
                <p class="message">
<?php echo $so['lang']['has_registered']; ?> <a href="<?php echo So_SeoLink('index.php?link1=signin'); ?>">
<?php echo $so['lang']['login']; ?>
                    </a>
                </p>
            </form>
        </div>
    </div>
</div>
<?php echo So_GetPage('footer/content'); ?>
<style>
    div#container-to-ajax-loading {
        height: auto;
    }
    body {
        background: url(<?php echo $so['config']['theme_url']; ?>/img/mountain.jpg) no-repeat center center fixed;
        height: -webkit-fill-available;
        background-position: center;
        background-size: 100% 100%;
    }
</style>
<script>
    $(function () {
        $('form#reset').ajaxForm({
            url: So_Requests() + '?type=password-recover',
            beforeSend: function () {

            },
            success: function (data) {
                if (data.status == 200) {
                    $('.Form-message').html(data.html);
                } else if (data.status == 400) {
                    $('.Form-message').html(data.errors);
                } else {
                    return false;
                }
            }
        });
    });
</script>