<div class="Footer module roaming-module Footer--slim Footer--blankBackground">
	<div class="flex-module">
		<div class="flex-module-inner js-items-container">
			<ul class="u-cf">
				<li class="Footer-item Footer-copyright copyright">© <?php echo date('Y'); ?> <?php echo $so['config']['site_name']; ?></li>
				<li class="Footer-item">
					<a class="Footer-link" href="<?php echo So_SeoLink('index.php?link1=about'); ?>" rel="noopener"><?php echo $so['lang']['terms_about']; ?></a>
				</li>
				<li class="Footer-item">
					<a class="Footer-link" href="<?php echo So_SeoLink('index.php?link1=tos'); ?>" rel="noopener"><?php echo $so['lang']['terms']; ?></a>
				</li>
				<li class="Footer-item">
					<a class="Footer-link" href="<?php echo So_SeoLink('index.php?link1=privacy'); ?>" rel="noopener"><?php echo $so['lang']['terms_privacy']; ?></a>
				</li>
			</ul>
		</div>
	</div>
</div>