<div id="block_error">
    <div>
        <h2>Error 404. &nbspOops <?php echo $so['lang']['not_found']; ?></h2>
        <p>
        </p>
    </div>
</div>
<style>
    .f-left{
        float:left;
    }
    .f-right{
        float:right;
    }
    .clear{
        clear: both;
        overflow: hidden;
    }
    #block_error{
        width: auto;
        max-width: 845px;
        height: 384px;
        border: 1px solid #cccccc;
        margin: 72px auto 0;
        -moz-border-radius: 4px;
        -webkit-border-radius: 4px;
        border-radius: 4px;
        background: #fff url(<?php echo $so['config']['theme_url']; ?>/img/block.gif) no-repeat 0 51px;
    }
    #block_error div{
        padding: 100px 40px 0 186px;
    }
    #block_error div h2{
        color: #218bdc;
        font-size: 24px;
        display: block;
        padding: 0 0 14px 0;
        border-bottom: 1px solid #cccccc;
        margin-bottom: 12px;
        font-weight: normal;
    }
</style>