<?php
$classUser = new User();
$classPost = new Post();
$search = $classUser->So_GetFollowing($so['profile']['user_id']);
?>
<!-- Friends -->
<div class="container" style="margin-top: initial;">
	<div class="row">
	<?php if (count($search) > 0) { 
	foreach ($search as $so['result']) { ?>
		<div class="col col-xl-3 col-lg-6 col-md-6 col-sm-6 col-6">
			<div class="ui-block">
				
				<!-- Friend Item -->
				
				<div class="friend-item">
					<div class="friend-header-thumb">
						<img src="<?php echo $so['result']['cover']; ?>" alt="friend">
					</div>
				
					<div class="friend-item-content">
						
						<div class="friend-avatar">
							<div class="author-thumb">
								<img width="62px" src="<?php echo $so['result']['avatar']; ?>" alt="author">
							</div>
							<div class="author-content">
								<a href="<?php echo $so['result']['url']; ?>" data-ajax="?link1=timeline&username=<?php echo $so['result']['username']; ?>" class="h5 author-name"><?php echo $so['result']['name']; ?></a>
								<div class="country"><?php echo $so['result']['location']; ?></div>
							</div>
						</div>
				
						<div class="swiper-container" data-slide="fade">
							<div class="swiper-wrapper">
								<div class="swiper-slide">
									<div class="friend-count" data-swiper-parallax="-500">
										<a href="javascript:void(0);" class="friend-count-item">
											<div class="h6"><?php echo $classPost->So_CountPostsUser($so['result']['user_id']); ?></div>
											<div class="title"><?php echo $so['lang']['twidleys']; ?></div>
										</a>
										<a href="javascript:void(0);" class="friend-count-item">
											<div class="h6"><?php echo $classUser->So_CountFollowingUser($so['result']['user_id']); ?></div>
											<div class="title"><?php echo $so['lang']['following']; ?></div>
										</a>
										<a href="javascript:void(0);" class="friend-count-item">
											<div class="h6"><?php echo $classUser->So_CountFollowersUser($so['result']['user_id']); ?></div>
											<div class="title"><?php echo $so['lang']['followers']; ?></div>
										</a>
									</div>
									<?php if ($so['result']['privacy'] == 1 && $so['result']['user_id'] != $so['user']['user_id']) { ?>
									<div class="control-block-button" data-swiper-parallax="-100">
										<a href="javascript:void(0);" title="<?php echo $so['lang']['messages']; ?>" id="result-get-chat" onclick="So_GetChatUser(<?php echo $so['result']['user_id']; ?>);" class="btn btn-control bg-purple">
											<svg style="margin-bottom: 5px;" class="svg-inline--fa fa-envelope fa-w-16" aria-hidden="true" data-prefix="fas" data-icon="envelope" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" data-fa-i2svg=""><path fill="currentColor" d="M502.3 190.8c3.9-3.1 9.7-.2 9.7 4.7V400c0 26.5-21.5 48-48 48H48c-26.5 0-48-21.5-48-48V195.6c0-5 5.7-7.8 9.7-4.7 22.4 17.4 52.1 39.5 154.1 113.6 21.1 15.4 56.7 47.8 92.2 47.6 35.7.3 72-32.8 92.3-47.6 102-74.1 131.6-96.3 154-113.7zM256 320c23.2.4 56.6-29.2 73.4-41.4 132.7-96.3 142.8-104.7 173.4-128.7 5.8-4.5 9.2-11.5 9.2-18.9v-19c0-26.5-21.5-48-48-48H48C21.5 64 0 85.5 0 112v19c0 7.4 3.4 14.3 9.2 18.9 30.6 23.9 40.7 32.4 173.4 128.7 16.8 12.2 50.2 41.8 73.4 41.4z"></path></svg>
										</a>
									</div>
									<?php } ?>
								</div>
								<?php if ($so['result']['privacy'] == 1 || $so['result']['user_id'] == $so['user']['user_id']) { ?>
								<div class="swiper-slide">
									<p class="friend-about" data-swiper-parallax="-500">
										<?php echo $so['result']['about']; ?>
									</p>
				
									<?php if (!empty($so['result']['day'])) { ?>
									<div class="friend-since" data-swiper-parallax="-100">
										<span><?php echo $so['lang']['birthday']; ?>:</span>
										<div class="h6"> <?php echo $so['result']['day']; ?> <?php echo $so['months'][$so['result']['month']]; ?> <?php echo $so['result']['year']; ?></div>
									</div>
									<?php } ?>
								</div>
								<?php } ?>
							</div>
				
							<!-- If we need pagination -->
							<div class="swiper-pagination"></div>
						</div>
					</div>
				</div>
				
				<!-- ... end Friend Item -->			
			</div>
		</div>
	<?php } } ?>
	</div>
</div>

<!-- ... end Friends -->