<?php $classUser = new User(); ?>
<?php if ($classUser->So_CheckFollowing($so['suggestion']['user_id']) === false) { ?>
<a href="javascript:void(0);" onclick="So_RegisterFollowSuggestion(<?php echo $so['suggestion']['user_id']; ?>);" class="accept-request">
	<span class="icon-add without-text">
		<?php echo $so['lang']['follow']; ?> 
	</span>
</a>
<?php } else { ?>
<a href="javascript:void(0);" onclick="So_RegisterFollowSuggestion(<?php echo $so['suggestion']['user_id']; ?>);" class="accept-request">
	<span class="icon-add without-text">
		<?php echo $so['lang']['following']; ?> 
	</span>
</a>>
</button>
<?php } ?>