<div class="pos-f-t">
	<nav class="navbar navbar-dark bg-dark">
		<button class="navbar-toggler pull-left" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
		  <span class="navbar-toggler-icon"></span>
		</button>
		<div style="text-align: center;width: calc(100% - 65px);float:  left;padding-right: 10%;">
			<a class="img-logo-header pull-left" href="<?php echo So_SeoLink('index.php?link1=home'); ?>">
				<img src="<?php echo $so['config']['site_url']; ?>/upload/images/logo.png?<?php echo time(); ?>" id="loading-ajax-icon" />
			</a>
		</div>
	</nav>
	<div class="collapse" id="navbarToggleExternalContent">
		<div class="uiContextualLayerPositioner _53ip _26fy _26f- uiLayer _4746 uiContextualLayerPositionerFixed" style="width: 1348px; left: 2px; top: 32px; z-index: 306; opacity: 1;">
			<div class="uiContextualLayer uiContextualLayerBelowLeft" aria-labelledby="">
			   <div class="_5v-0 _53il" style="width: 1350px;">
				  <div class="_53ij">
					 <div>
						<div>
						   <table alignv="top" class="_397x uiGrid _51mz _5f0n" cols="5" cellspacing="0" cellpadding="0">
							  <tbody>
								 <tr class="_51mx">
									<td id="megamenu_column_create_and_manage_header" class="_5u-y _4ach autofocus _51m- vTop">
									   <div class="_4h1p">
											<div>
												<span class="_4h1q _kcu">
													<i class="_kcw img sp_0BJZ7OsJ-wb sx_522f8b" alt=""></i>
												</span>
												<span class="_4h1r"><?php echo $so['lang']['create_and_manage']; ?></span>
											</div>
									   </div>
									</td>
								 </tr>
								 <tr class="_51mx">
									<td id="megamenu_column_create_and_manage_list" class="_4ach autofocus _51m- vTop">
									   <ul class="_6yb">
										  <li class="_6yc">
											<div>
												<a href="<?php echo So_SeoLink('index.php?link1=adsense&type=ads_manager'); ?>" class=" _52pb pointer"><?php echo $so['lang']['ads_manager']; ?></a>
											</div>
										  </li>
									   </ul>
									</td>
								 </tr>
								 <tr class="_51mx">
									<td colspan="5" class="_4ach autofocus _51mw _51m- vTop">
									   <div class="_3rj-"><span class="_3rj_ _kcu"><i class="_kcw img sp_wRWO7YVkqaf sx_65927d" alt=""></i></span><span class="_3rk0"><?php echo $so['config']['site_name']; ?></span></div>
									</td>
								 </tr>
							  </tbody>
						   </table>
						</div>
					 </div>
				  </div>
			   </div>
			</div>
		</div>
	</div>
</div>
<script>
$(function () {
	$('.pos-f-t button.navbar-toggler.pull-left').click(function () {
		$('.lightbox').toggle();
	});
});
</script>
<style>
nav.navbar.navbar-dark.bg-dark {
	z-index: 4003;
}
.uiContextualLayer {
    position: absolute;
	z-index: 4003;
}
._53ip ._53il {
    padding-top: 0px;
}
._53ip ._5v-0 {
    padding-bottom: 10px;
}
._26fy ._5v-0 {
    transition: width 250ms;
}
._53ip ._53ij {
    border: 1px solid #8c8c8c;
    border: 1px solid rgba(0, 0, 0, .45);
    border-bottom: 1px solid #666;
    box-shadow: 0 3px 8px rgba(0, 0, 0, .3);
}
._47q2 ._26fy, ._26fy ._53ij {
    left: -2px;
    overflow: hidden;
}
._53ij {
    background: #fff;
    position: relative;
}
._5f0n {
    table-layout: fixed;
    width: 100%;
}
._51mz {
    border: 0;
    border-collapse: collapse;
    border-spacing: 0;
}
._51mz ._51m-:first-child {
    padding-left: 0;
}
._51mx:first-child>._51m- {
    padding-top: 0;
}
._4ach:last-child {
    border-right: none;
}
.uiGrid .vTop {
    vertical-align: top;
}
._4ach:last-child ._4h1p {
    width: 100vw;
}
._4h1p {
    background-color: #f5f7f8;
    box-sizing: border-box;
    display: flex;
    flex-direction: column;
    height: 56px;
    justify-content: center;
    padding: 20px calc(10% - 5px);
    width: 100%;
}
._4h1q {
    vertical-align: top;
}
._kcu {
    display: inline-block;
    line-height: 0;
    padding: 2px;
}
.sp_0BJZ7OsJ-wb.sx_522f8b {
    width: 14px;
    height: 14px;
    background-position: 0 -2866px;
}
i.img {
    -ms-high-contrast-adjust: none;
}
.sp_0BJZ7OsJ-wb {
    background-image: url(https://static.xx.fbcdn.net/rsrc.php/v3/yG/r/kvd3kJPB0N3.png);
    background-size: auto;
    background-repeat: no-repeat;
    display: inline-block;
    height: 20px;
    width: 20px;
}
._kcw {
    vertical-align: inherit;
}
._4h1r {
    color: #5b5c5e;
    display: inline-block;
    font-size: 13px;
    font-weight: bold;
    margin-left: 8px;
    padding-top: 1px;
    width: 84%;
}
._51mz ._51m-:first-child {
    padding-left: 0;
}
._4ach:last-child {
    border-right: none;
}
.uiGrid .vTop {
    vertical-align: top;
}
._6yb {
    box-sizing: border-box;
    display: inline-block;
    height: 100%;
    margin-bottom: 24px;
    padding: 12px calc(10% - 5px) 16px;
    width: 100%;
}
._6yb ._6yc {
    color: #929598;
    font-size: 13px;
}
._52pb {
    color: #929598;
}
._52pb, ._3aau, ._ru3 {
    display: block;
    padding: 8px 0;
}
._51mz ._51m-:first-child {
    padding-left: 0;
}
._51mx:last-child>._51m- {
    padding-bottom: 0;
}
._4ach:last-child {
    border-right: none;
}
._51mz ._51mw {
    padding-right: 0;
}
.uiGrid .vTop {
    vertical-align: top;
}
._3rj- {
    background-color: #fbfbfb;
    height: 55px;
    margin: 0;
    padding: 14px 10px;
    width: 100vw;
}
._3rj- ._3rj_ {
    vertical-align: top;
}
._kcu {
    display: inline-block;
    line-height: 0;
    padding: 2px;
}
.sp_wRWO7YVkqaf.sx_65927d {
    background-position: 0 -58px;
}
i.img {
    -ms-high-contrast-adjust: none;
}
.sp_wRWO7YVkqaf {
    background-image: url(https://static.xx.fbcdn.net/rsrc.php/v3/ys/r/wq2ynmtV_CR.png);
    background-size: auto;
    background-repeat: no-repeat;
    display: inline-block;
    height: 16px;
    width: 16px;
}
._kcw {
    vertical-align: inherit;
}
._3rj- ._3rk0 {
    color: #929598;
    display: inline-block;
    font-size: 12px;
    margin-left: 8px;
    position: relative;
    top: 4px;
    width: 78%;
}
._5u1r, ._5u1r button, ._5u1r input, ._5u1r label, ._5u1r select, ._5u1r td, ._5u1r textarea {
    font-family: Helvetica, Arial, Lucida Grande, sans-serif;
    font-size: 12px;
}
@media screen and (min-width: 1160px) {
	._4h1r, ._6yb ._6yc {
		font-size: 14px;
	}
}
</style>